name: "Test GitHub Pages Deployment"

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Create Test Site
        run: |
          mkdir _site
          echo "<h1>Hello, GitHub Pages!</h1>" > _site/index.html

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}